#!/usr/bin/env python3
"""
 Arduino Config Generator
Generates Arduino configuration from .env file
"""

from config import config
import os


def escape_c_string(value):
    """Escape a Python string so it is a safe C/C++ string-literal *body*.

    The generated ``config.h`` embeds the WiFi SSID and password between double
    quotes (``const char* WIFI_SSID = "...";``). WPA2 credentials may legally
    contain a double quote or backslash, and an unescaped one would either break
    the firmware build (``"pa"ss"`` is a syntax error) or silently corrupt the
    value (a trailing ``\\`` would escape the closing quote). Escape the
    characters that are special inside a C string literal so the emitted line is
    always well-formed; ordinary characters (including spaces) pass through
    unchanged.
    """
    return (
        str(value)
        .replace("\\", "\\\\")  # backslash first, so we don't double-escape below
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "\\r")
        .replace("\t", "\\t")
    )


def generate_arduino_config():
    """Generate Arduino configuration header from Python config"""

    wifi_ssid = escape_c_string(config.WIFI_SSID)
    wifi_password = escape_c_string(config.WIFI_PASSWORD)

    arduino_config = f'''// Auto-generated configuration from Python config
// Do not edit this file directly - edit .env instead and run generate_arduino_config.py

#ifndef CONFIG_H
#define CONFIG_H

// WiFi Configuration
const char* WIFI_SSID = "{wifi_ssid}";
const char* WIFI_PASSWORD = "{wifi_password}";

// Servo Configuration
#define PAN_HOME {config.PAN_HOME}
#define TILT_HOME {config.TILT_HOME}
#define CENTER_ANGLE {config.CENTER_ANGLE}

// Servo pins (hardcoded for hardware)
#define PAN_PIN 18
#define TILT_PIN 19
#define BLASTER_PIN 21

// PWM settings
#define PWM_FREQ 50
#define PWM_RES 16

// Servo timing
#define SERVO_MIN_US 1000
#define SERVO_MAX_US 2000
#define SERVO_CENTER_US 1500

#endif // CONFIG_H
'''

    # Write to Arduino project directory
    config_path = "ESP32_OTA_Servo/config.h"
    with open(config_path, 'w') as f:
        f.write(arduino_config)

    print(f"SUCCESS: Generated Arduino config: {config_path}")
    print(f" WiFi SSID: {config.WIFI_SSID}")
    print(f" WiFi Password: {'*' * len(config.WIFI_PASSWORD)}")
    print(f" Servo Home: Pan={config.PAN_HOME}°, Tilt={config.TILT_HOME}°")
    print(f"\n Include this in your Arduino code with: #include \"config.h\"")

if __name__ == "__main__":
    # Check if .env exists
    if not os.path.exists('.env'):
        print("ERROR: .env file not found!")
        print(" Create .env from template:")
        print(" 1. Copy env_template.txt to .env")
        print(" 2. Update with your WiFi credentials")
        print(" 3. Run this script again")
        exit(1)

    generate_arduino_config()
